language: r
sudo: false
cache: false

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - r: oldrel
      os: osx
    - r: devel
      os: osx

before_isntall:
  - Rscript -e 'install.packages("janitor")'

script:
  - Rscript -e "rmarkdown::render('notebooks/complete/atlas-01-dataCleaning-complete.Rmd')"
  - Rscript -e "rmarkdown::render('notebooks/complete/atlas-02-dataExploration-complete.Rmd')"
  - Rscript -e "rmarkdown::render('notebooks/complete/atlas-03-dataPlotting-complete.Rmd')"
